### ISSUE TITLE
PHP Warning issued when no quotes available

### ISSUE THREAD

**Issue by lat9** [OldNGreyBMR/aupost#15]
Seeing logs like the following (running 2.5.6d):
```
[09-Nov-2024 00:18:27 Australia/Sydney] Request URI: /index.php?main_page=shopping_cart, IP address: xx.xx.xx.xx, Language id 1
#0 /home/mysite/includes/modules/shipping/aupost.php(693): zen_debug_error_handler()
#1 /home/mysite/includes/classes/shipping.php(201): aupost->quote()
#2 /home/mysite/includes/modules/shipping_estimator.php(151): shipping->quote()
#3 /home/mysite/includes/templates/bootstrap/templates/tpl_shopping_cart_default.php(227): require('/home/mysite...')
#4 /home/mysite/includes/templates/bootstrap/common/tpl_main_page.php(216): require('/home/mysite...')
#5 /home/mysite/index.php(94): require('/home/mysite...')
--> PHP Warning: Undefined variable $methods in /home/mysite/includes/modules/shipping/aupost.php on line 693.
```

I'll suggest adding
```php
$methods = [];
```

... right before the loop's start on line 495:
https://github.com/OldNGreyBMR/aupost/blob/88962fd7fe418d5ec9b6087e3ac8e51a2dff3b05/includes/modules/shipping/aupost.php#L493-L496

**Comment by OldNGreyBMR** [comment]
Thank you
