### ISSUE TITLE
Missing method 'id' for excess length, volume and weight quotes

### ISSUE THREAD

**Issue by lat9** [OldNGreyBMR/aupost#19]
In this section

https://github.com/OldNGreyBMR/aupost/blob/cdc9f03b9506d8100557eda2874ae38f1fc7552c/zc_plugins/AustraliaPost/V3.0.0/catalog/includes/modules/shipping/aupost.php#L723-L761

... which results in the following one-page checkout log:
```
[28-Nov-2024 12:41:54 Australia/Sydney] Request URI: /index.php?main_page=checkout_one, IP address: ***, Language id 1
#0 [internal function]: zen_debug_error_handler()
#1 /includes/templates/template_default/templates/tpl_modules_checkout_one_shipping.php(39): trigger_error()
#2 /includes/templates/bootstrap/templates/tpl_modules_opc_shipping_choices.php(53): require('/home/***...')
#3 /includes/templates/bootstrap/templates/tpl_checkout_one_default.php(69): require('/home/***...')
#4 /includes/templates/bootstrap/common/tpl_main_page.php(233): require('/home/***...')
#5 /index.php(94): require('/home/***...')
--> PHP Notice: Missing id element from one or more shipping quotes. Enabled modules: aupost.php;aupostoverseas.php;flat.php;freeshipper.php;item.php;storepickup.php;table.php, quotes:
[
{
"id": "aupost",
"module": "Flat Rate",
"methods": [
{
"title": " (AusPost excess length)",
"cost": "250"
}
],
"tax": 0
},
{
"id": "table",
"module": "Table Rate",
"methods": [
{
"id": "table",
"title": "Best Way",
"cost": 14.5
}
],
"tax": 0
}
] in /includes/templates/template_default/templates/tpl_modules_checkout_one_shipping.php on line 39.
```

**Comment by OldNGreyBMR** [comment]
fixed in v2.5.7a for auspost and auspostoverseas
